server:
  port: 8080

spring:
  application:
    name: demo-application
  boot:
    admin:
      client:
        url: http://localhost:1111
        username: admin
        password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  file:
    name: demo-application-service.log
    max-history: 5
    max-size: 10MB

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'